# 🐳 Docker Compose para desenvolvimento local
# Use este arquivo para rodar o sistema completo localmente

version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: relatorios_db
    environment:
      POSTGRES_DB: relatorios_db
      POSTGRES_USER: relatorios_user
      POSTGRES_PASSWORD: relatorios_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - relatorios_network

  # Backend Node.js
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: relatorios_backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: relatorios_db
      DB_USER: relatorios_user
      DB_PASSWORD: relatorios_password
      JWT_SECRET: sua_chave_jwt_super_secreta_aqui
      CORS_ORIGIN: http://localhost:3000,http://localhost:3002,http://localhost:3005
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - relatorios_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Next.js (opcional - pode rodar localmente)
  frontend:
    image: node:18-alpine
    container_name: relatorios_frontend
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_NAME: Sistema de Relatórios
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - relatorios_network

volumes:
  postgres_data:

networks:
  relatorios_network:
    driver: bridge

