[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.buildCommand]
command = "cd backend && npm ci --only=production"

[build.installCommand]
command = "cd backend && npm ci --only=production"
